<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net48</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <AssemblyName>antihero</AssemblyName>
        <RootNamespace>antihero</RootNamespace>
        <OutputType>Library</OutputType>
    </PropertyGroup>
    <PropertyGroup>
        <GamePath Condition="$([MSBuild]::IsOSPlatform('Windows'))">$(UserProfile)\Steam\steamapps\common\Bit Heroes</GamePath>
        <GamePath Condition="$([MSBuild]::IsOSPlatform('Linux'))">$(HOME)/.local/share/Steam/steamapps/common/Bit Heroes</GamePath>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Lib.Harmony" Version="2.3.3" />
        <PackageReference Include="rainbowblood.UniverseLib.Mono" Version="2.*" />
    </ItemGroup>
    <ItemGroup>
        <Reference Include="MelonLoader">
            <HintPath>$(GamePath)/MelonLoader/net35/MelonLoader.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="Assembly-CSharp">
            <HintPath>$(GamePath)/Bit Heroes_Data/Managed/Assembly-CSharp.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="UnityEngine">
            <HintPath>$(GamePath)/Bit Heroes_Data/Managed/UnityEngine.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="UnityEngine.CoreModule">
            <HintPath>$(GamePath)/Bit Heroes_Data/Managed/UnityEngine.CoreModule.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="UnityEngine.UI">
            <HintPath>$(GamePath)/Bit Heroes_Data/Managed/UnityEngine.UI.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="UnityEngine.TextRenderingModule">
            <HintPath>$(GamePath)/Bit Heroes_Data/Managed/UnityEngine.TextRenderingModule.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="UnityEngine.InputLegacyModule">
            <HintPath>$(GamePath)/Bit Heroes_Data/Managed/UnityEngine.InputLegacyModule.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="SmartFox2X">
            <HintPath>$(GamePath)/Bit Heroes_Data/Managed/SmartFox2X.dll</HintPath>
            <Private>false</Private>
        </Reference>
    </ItemGroup>
</Project>
